services:
  web:
    build: .
    container_name: weather_project
    ports:
      - '5000:5000'
    environment:
      - redis_url=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:latest
    container_name : redis
    ports:
      - "6379:6379"
    
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_file worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL = redis://redis:6379/0
      - CELERY_RESULT_BACKEND = redis://redis:6379/0

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A celery_file beat --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL = redis://redis:6379/0
      - CELERY_RESULT_BACKEND = redis://redis:6379/0